# Generated by Django 4.1.1 on 2022-11-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='like',
            new_name='liked_by',
        ),
    ]
