# Generated by Django 4.1.1 on 2022-11-09 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_like_posts_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='liked_by',
        ),
    ]
